### ISSUE TITLE
polygon library ?

### ISSUE THREAD

**Issue by jeanroukas** [WestXu/no_fit_polygon_py3#1]
Hi,
I'm not sure if you will have time to see this from singapore, and I know this project is 4 years old. 
I try hard to make this work for a learning project, but i'm not sure of the polygon library you use. 
I try with Polygon3 as I saw in requierement.txt, but it didn't work.

I get this error with python test_nfp.py:

Traceback (most recent call last):
  File "C:\Users\lprad\gcode_clay_processor\experimental\nfp\test_nfp.py", line 28, in <module>
    content_loop_rate(best, n, loop_time=2)  # T7 , T4
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\-\experimental\nfp\nfp_function.py", line 678, in content_loop_rate
    draw_result(res['placements'], n.shapes, n.container, n.container_bounds)
  File "C:\-\experimental\nfp\nfp_function.py", line 392, in draw_result      
    shapes.append(Polygon(contour))
                  ^^^^^^^^^^^^^^^^
TypeError: 'module' object is not callable

Have a good day.

**Comment by WestXu** [comment]
This was just a py3 fork of the following repo. You should check it out. 

https://github.com/liangxuCHEN/no_fit_polygon

**Comment by jeanroukas** [comment]
thanks for the answer !
